### ISSUE TITLE
the DNS record should be updated

### ISSUE THREAD

**Issue by robertoostenveld** [Radboud-University/osc-nijmegen#12]
see https://help.github.com/articles/using-a-custom-domain-with-github-pages/

it now resolves to an IP address
```
mac011> nslookup openscience-nijmegen.nl
Server:		192.168.1.12
Address:	192.168.1.12#53

Non-authoritative answer:
Name:	openscience-nijmegen.nl
Address: 37.228.153.11
```

**Comment by Frederik-D-Weber** [comment]
... in progress at hoster for CNAME entry pointing to the server radboud-university.github.io/osc-nijmegen/
lets hope they are quick and I got it right.

**Comment by Frederik-D-Weber** [comment]
...
for now only the subdomain (with preceding www)
www.openscience-nijmegen.nl
https://network-tools.com/nslook/Default.asp?domain=www.openscience-nijmegen.nl&type=255&server=8.8.8.8&class=1&port=53&timeout=5000&go.x=0&go.y=0

apex/naked domain CNAME entry hopefully following soon as well.

**Comment by Frederik-D-Weber** [comment]
openscience-nijmegen.nl now online, subdomain www.openscience-nijmegen.nl points (as it should) to openscience-nijmegen.nl
The renewed ssl certificate from github still needs until tomorrow (24 hour lock) to be renewable for issue-free https access via standard browser.
@KristijanArmeni could you check again tomorrow if you can enable it.

**Comment by KristijanArmeni** [comment]
I tested on Firefox (also after clearing cache) and Chrome. Links with naked/apex domain (without `www`) work OK. Https is enforced under settings. Links with subdomain result in a safety warning (https not configured for those). I'm willing to consider this issue sufficiently solved, but for the rest: @Frederik-D-Weber are we sure all is configured well with the DNS service?

See [this](https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/) page for configuring both apex and subdomains. Might here be a clue?:

>**Setting up an apex domain**
To set up an apex domain, such as example.com, you must configure an ALIAS, ANAME, or A record with your DNS provider.
**Setting up a www subdomain**
To set up a www subdomain, such as www.example.com you must configure a CNAME record with your
DNS provider.

Currently our CNAME points to openscience-nijmegen.nl.
