### ISSUE TITLE
"Issues" on contribute page doesn't link here

### ISSUE THREAD

**Issue by christinabergmann** [Radboud-University/osc-nijmegen#13]
https://openscience-nijmegen.nl/_pages/contribute/ also doesn't have a menu item.

**Comment by KristijanArmeni** [comment]
Thanks @christinabergmann! Added :)

**Comment by KristijanArmeni** [comment]
A propos the menu item. I guess for a page with a single heading like contribute, it doesn't make sense to have toc or navigation side bar? Or were you referring to something else?

**Comment by christinabergmann** [comment]
No I think this works, I was just trying to suggest ways to make it easier to contribute, in the spirit of openness! :)
