### ISSUE TITLE
add contributors page/README to repo

### ISSUE THREAD

**Issue by KristijanArmeni** [Radboud-University/osc-nijmegen#17]
If there are more contributors eventually, it would be good to have a 'contributors' page where we give credit. Or do it automatically.

This project gives a good starting point:
- https://allcontributors.org/

**Comment by norok2** [comment]
I could contribute to this!

**Comment by KristijanArmeni** [comment]
@all-contributors please add @norok2 for tool

**Comment by KristijanArmeni** [comment]
@all-contributors add @norok2 for tool

**Comment by johalgermissen** [comment]
@all-contributors add @evapoort for eventOrganizing ideas blog
