### ISSUE TITLE
pages cropped

### ISSUE THREAD

**Issue by KristijanArmeni** [Radboud-University/osc-nijmegen#24]
### Description
Noticed that pages are not displayed in full or do not allow scrolling. Happens on Firefox and Chrome, on work PC and my laptop. For example:

<img width="590" alt="oscn_bug" src="https://user-images.githubusercontent.com/14061041/67468986-c3d4e400-f64b-11e9-87d0-17041a2fbb0b.png">

Not sure whether I accidentally made some configuration changes recently or if it is a [template](https://github.com/mmistakes/minimal-mistakes) issue.

### What can be done?
- check whether it is reproduced on other machines  
- find the source of this bug (our page or template) 
- fix it :)

**Comment by Frederik-D-Weber** [comment]
potential fix in the footer css "position: absolute;" disables?

**Comment by Frederik-D-Weber** [comment]
merged the pull request #25 to fix this issue, hope it will not break anyting else

**Comment by Frederik-D-Weber** [comment]
changed it again to "position: relative" hope that is more conservative
