### ISSUE TITLE
create contents in about.md

### ISSUE THREAD

**Issue by KristijanArmeni** [Radboud-University/osc-nijmegen#5]
Create contents in the 'About' page. The about section should minimally include the following:
- goals of the community
- types of activities
- targeted members of the community

Proposed action:

- [x] prepare a draft either by modifying /_pages/about.md directly on GitHub and create a pull request or use a collaborative editing tool (google docs) and propose contents there.

Possible structure:
In commit e4c5e55 I created a simple sidebar for "About". Which can be used as a starting point when writing contents.

**Comment by KristijanArmeni** [comment]
Added some first temporary contents in 76505bd.

**Comment by christinabergmann** [comment]
Hi, just some feedback, it might be nice to add a "who we are" section?

**Comment by KristijanArmeni** [comment]
Thanks @christinabergmann. There is a section "Who are we?" already under About, but a very general one. I added now also a separate page about the [Organizing team](https://openscience-nijmegen.nl/_pages/team/), to put some names to the initiative. It is visible in the sidebar under About.

**Comment by christinabergmann** [comment]
Ah fantastic, this is much more approachable and human now! And yay for doing this! I'm looking forward to your activities.
