### ISSUE TITLE
organize git/GitHub workshop (collab with Dondrite)

### ISSUE THREAD

**Issue by KristijanArmeni** [Radboud-University/osc-nijmegen#52]
## Summary

Organize a short workshop on basics of Git/Github for the Donders CNS masters students. 
**date**: Nov 28, 15.00-17.00

https://openscience-nijmegen.nl/git-workshop/
OSF repo: https://doi.org/10.17605/OSF.IO/ZVKYX 

### contents
Part I:
- [x] ~intro contents/slides~ @KristijanArmeni 
- [x ] ~demo(s)~
  - [x ] ~basic git cycle demo (clone, pull, push, PR)~
  - [x] ~come up with a personal use case~ (@aranas)
  - [x] ~brainstorm 'disaster scenarios'~ (@aranas)

Part II:  
- [x] ~create the hands-on project~
  - [x] ~brainstorm issues for the hands-on~

### logistics
- [x] ~check the options to use git (command line etc) in the Trigon instruction room (@KristijanArmeni )~
- [x] ~check the options to host workshop materials, e.g. Zenodo/OSF  (@aranas, @KristijanArmeni)~
- [x] make sure git and some https://git-scm.com/download/win is installed in the instruction room (@KristijanArmeni, maybe organizers)
- [x] ~test configuration of git command line on instruction room PCS~  
- [x] ~spell out the account preparations/guidelines on the website~  
### logistics:
- computers in the instruction room run on Windows, we need to let the TG know (at least 14d in advance) what needs to be installed
- we can open a new OSF project for storing the materials
- tool to be installed: https://git-scm.com/download/win

**Comment by aranas** [comment]
here is one OSF style example of hosting workshop material: https://osf.io/r73y9/
I quickly checked Zenodo some more and honestly cannot make out any differences to OSF. They both allow you to link your account to ORCID ID, they both allow to create DOIs, so I guess either would be fine

**Comment by robertoostenveld** [comment]
A few years back Github (the company) had a lot of activities in student training. See https://education.github.com/. It has gotten quieter (or I might have signed off from the specific mailing list), but I guess you can still find general training material.

Some 5 or 6 year ago we did a small github training hackathon for the FieldTrip team back then, with an external git expert: the boyfriend of one of the PhD students, he was working at an IT company. We still have the repository, see [commits here](https://github.com/fieldtrip/playground/commits/master). What worked there was to have a small team (i.e. few people in a single repository) and work on the collaboration (i.e. different people successively working on one text file), but also important is to avoid merge conflicts which are (and remain) confusing.

**Comment by KristijanArmeni** [comment]
Thanks for sharing this @robertoostenveld. Will check this.
Thanks @aranas. Let me check the state of affairs with the OSCN OSF space then. Maybe we can use that (to avoid hosting on personal accounts). Will report back.

**Comment by robertoostenveld** [comment]
you should also check https://software-carpentry.org, they typically have videos and good hands-on material that is (by design) easy to clone and reuse. Although, ... on https://software-carpentry.org/lessons/ I only see a plain git, not a github lesson.

**Comment by aranas** [comment]
Resources/helpful material:
https://ohshitgit.com/

**Comment by KristijanArmeni** [comment]
@aranas I added a more explicit workshop program with timeline & contents to the website: https://openscience-nijmegen.nl/git-workshop/ :rocket:

I think this is more or less how we discussed it, but just shout if anything seems different (the times should be taken as rough indications).

I can fill in the prep guidelines and useful materials later today.

**Comment by aranas** [comment]
okay, thanks! Let's see if we will really stick to the exact timing :sweat_smile:

I wonder whether the "how things can go wrong" from part one and the "troubleshooting" from the wrap-up have quite some overlap. Maybe better to keep this together under one heading? 
actually I think the more little things (e.g. the difference of git diff vs git diff --staged) is probably something we could easily build into the issues for the hands-on and the more serious troubleshooting scenarios (so far I have created slides for a simple case of rebasing and git reset) are better to safe for last. But in this case we wouldn't need to mention these things in part one.

What do you think?

**Comment by KristijanArmeni** [comment]
Indeed, serious troubleshooting scenarios go at the end. I fixed the description to reflect that. And yes, let's try to strategically include the smaller bits into issues for the hands-on (we should use labels to show what each issue focuses on).

**Comment by KristijanArmeni** [comment]
@aranas I will close this issue :tada: You OK to be listed as a contributor (contents, tutorial, event organizing) on this [repo's readme](https://github.com/Radboud-University/osc-nijmegen/blob/master/README.md)?

**Comment by aranas** [comment]
sure happy to!

**Comment by KristijanArmeni** [comment]
@all-contributors please add @aranas for eventOrganizing, tutorial, talk
