### ISSUE TITLE
add ReproducibiliTea page on website

### ISSUE THREAD

**Issue by eirini-zormpa** [Radboud-University/osc-nijmegen#54]
we should probably have a dedicated page with the schedule (dates/location) and the papers etc. to be discussed. It would probably also be good for the individual events to appear in the agenda.

**Comment by KristijanArmeni** [comment]
Yes, I agree. It would be good to have a fixed tab/page. The page should have the following info:
- brief initiative description and link to existing reproducibilitea website
- link to Nijmegen OSF repo
- schedule

I see two options:

- new page under Resources tab
- new page under Agenda 
- new tab 'Initiatives' and new page there

And yes, separate agenda items would be then added anyway (separately from the page) for each journal club.

**Comment by eirini-zormpa** [comment]
great! I think a new tab in 'Initiatives' makes most sense, but it's probably also the most work >.<

**Comment by KristijanArmeni** [comment]
@eirini-zormpa in ca52c53 I added the initiatives tab and a side bar with the link to the reproducibilitea home page. I think it's sufficiently empty :blush:

- [initiatives tab](https://github.com/Radboud-University/osc-nijmegen/blob/master/docs/_pages/initiatives.md)
- [reproducibilitea](https://github.com/Radboud-University/osc-nijmegen/blob/master/docs/_pages/reproducibilitea.md)

I would first fill up the basic information on the reproducitbilitea and then see what can be improved under initiatives.

**Comment by KristijanArmeni** [comment]
@eirini-zormpa I created a branch [rtea](https://github.com/Radboud-University/osc-nijmegen/tree/rtea) for this issue, but I didn't revert changes in master branch. Two ways to work now:

- work on rtea branch in this repo 
- sync your own fork, and work on a branch there (preferred typically, but you need to clone locally this repo first before you can then sync your fork)

Whatever works  best 😃

**Comment by KristijanArmeni** [comment]
Page created in #55 and #57. This closes this issue. :tada: 

As a followup, I think the page could do with a title (can be simply added in the yaml frontmatter as `title: "ReproducibiliTea"` ).

**Comment by KristijanArmeni** [comment]
Added titlte in 68fc49ace. Closing this. I suggest to open new separate issues for content-related discussions on the ReproducibiliTea subpage. :tada:
