### ISSUE TITLE
paper suggestions for ReproducibiliTea

### ISSUE THREAD

**Issue by eirini-zormpa** [Radboud-University/osc-nijmegen#67]
It'd be nice to add a place on the ReproducibiliTea page where people can suggest papers to discuss. They'd need to provide: name of paper (ideally doi), their name, their email.
This could just be a linked google doc.

**Comment by KristijanArmeni** [comment]
Yes, I agree. The leanest option is a link to a shared google doc with edit permissions. Then all the functionality is already in place (comments, deleting, shuffling). The the OSF account is not needed then, only our google drive storage. Unless we used another OSF functionality (wiki?) which I am not familiar with.

The organizers would then take care that the page with the schedule is updated regularly when suggestions are confirmed.

Shall we do that? 

(If we see a better way of managing this, we can always change later.)
