### ISSUE TITLE
Typo on Poster

### ISSUE THREAD

**Issue by heytitle** [Radboud-University/osc-nijmegen#69]
Hi,

This is not related to the web, and feel free to close it. I just want to let you know that there seems to be a small typo on the latest poster. 

The event url should be `https://openscience-nijmegen.nl/reprotea-meeting2/` not `https://openscience-nijmegen.nl/reprotea_meeting2/`, replacing `_ (underscore)` with `- (dash)`.

![IMG_2614](https://user-images.githubusercontent.com/1214890/73918805-9b9f8700-48c2-11ea-9be7-e20657d86562.JPG)

**Comment by KristijanArmeni** [comment]
Thanks @heytitle for spotting this, eagle eyes! Perhaps @eirini-zormpa and @johalgermissen can check whether this Feb ReproTea link has been shared elsewhere where it can be corrected.

**Comment by eirini-zormpa** [comment]
amazing @heytitle! thank you, I will change this in the MPI posters :)
