### ISSUE TITLE
create logo and header image for home page

### ISSUE THREAD

**Issue by KristijanArmeni** [Radboud-University/osc-nijmegen#8]
We need a logo, perhaps simply OSCN in a circle or so. Some wide header image would be nice too on the home page (related to Nijmegen campus or so).

**Comment by JoKeyser** [comment]
As a potential starting point, here is was the OSC Utrecht uses on their website:

![cropped-logo-oscu-v2](https://user-images.githubusercontent.com/8722846/44911478-43587300-ad27-11e8-854a-47ae13edc6dd.png)

One simple way forward might just be to replace Utrecht with Nijmegen...?

**Comment by KristijanArmeni** [comment]
Thanks @JoKeyser, good idea. And perhaps replace yellow with red to make it more Nijmegen-ish. I'll ask with Utrecht folks if there's materials that we could adapt and credit if needed.

**Comment by JoKeyser** [comment]
@KristijanArmeni nice idea with the colors. I've made a quick draft to visualize it, using the "Radboud Red". The fonts don't match, so it might still be nice to ask the OSCU for their file. 

![draft1_logo-osci svg](https://user-images.githubusercontent.com/8722846/44924539-e4592500-ad4b-11e8-9008-96cf38ca3945.png)

**Comment by Frederik-D-Weber** [comment]
... looks good already, and adorable: people of all colors raching out to eachother around the globe for science, .... but wait, isn't this the Ubuntu logo already, turned by ~60°

**Comment by JoKeyser** [comment]
@Frederik-D-Weber you might be right, they're quite similar, it's their "circle of friends", see https://design.ubuntu.com/brand/ubuntu-logo/

![ubuntu-logo32](https://user-images.githubusercontent.com/8722846/44960877-85400f80-af07-11e8-9ca1-d99ee48c80cc.png)

**Comment by JoKeyser** [comment]
And yet, they're not identical... not sure if this could be a problem.

**Comment by KristijanArmeni** [comment]
@JoKeyser Great, thanks for the draft, looks nice to me! As for the resemblance, I also agree it's very similar; I'll ask the Utrecht bunch about this, just in case they've thought it through perhaps already.

**Comment by KristijanArmeni** [comment]
In cf9ad51 I added an image to the header (to fix the basic esthetics). As for the Ubuntu issue, I asked Anita from OSCU and they haven't really noticed this, but they also don't see it as an issue.

As for our logo, Anita who authored the OSCU logo, sent me the OSCN version as drafted above, but it is not in vector graphics and I did not manage to add it to the header image. I'll put it in the /images folder.

In any case, if a new header image is created, it has to be put under /assets/images/ and linked with absolute path in "index.md" under `overlay_image: "path_to_file"`

**Comment by JoKeyser** [comment]
@KristijanArmeni so if Utrecht can't deliver a better version, should I then upload my svg version (create a pull request with it)?

**Comment by KristijanArmeni** [comment]
@JoKeyser Yeah, that would be great! If you upload it with through PR, then I can try and set it up on the site. Or if you feel lucky and want to create a PR with a new header image on the site, that's fine by me as well. :)

**Comment by JoKeyser** [comment]
@KristijanArmeni I've opened PR #9 , sorry couldn't be bothered yet to check out how to add it to the website :).

**Comment by KristijanArmeni** [comment]
Cool, thanks @JoKeyser for this. Perfect that we have it in vector graphics, we can fool with positioning and esthethics at a later point.

Thanks @Frederik-D-Weber for a quick and dirty fix. The effect is massive and assertive :), I agree ... esthetics can wait.
